src/Visualizer/Controllers/VisualizerController.cs
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Collections.Generic;
using Risk.Shared;


namespace Visualizer.Controllers
{
    public class VisualizeController : Controller
    {
        private readonly IHttpClientFactory clientFactory;
        

        public VisualizeController(IHttpClientFactory clientFactory)
        {
            this.clientFactory = clientFactory;
        }

        [HttpGet("AreYouThere")]
        public string AreYouThere()
        {
            return "yes";
        }


        [HttpPost("gameOver")]
        public IActionResult GameOver([FromBody] GameOverRequest gameOverRequest)
        {
            return Ok(gameOverRequest);
        }
    }
}

src/Visualizer/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Json;
using Risk.Shared;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Caching.Memory;

namespace Visualizer.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IConfiguration configuration;
        private readonly IMemoryCache memoryCache;

        public IndexModel(IHttpClientFactory httpClientFactory, IConfiguration configuration, ColorGenerator colorGenerator, IMemoryCache memoryCache)
        {
            this.httpClientFactory = httpClientFactory;
            this.configuration = configuration;
            ColorGenerator = colorGenerator;
            this.memoryCache = memoryCache;
        }

        public GameOverRequest gameOverRequest { get; set; }
        public GameStatus Status { get; set; }
        public int MaxRow { get; private set; }
        public int MaxCol { get; private set; }
        public ColorGenerator ColorGenerator { get; }



        public async Task OnGetAsync()
        {
            Status = await httpClientFactory
                .CreateClient()
                .GetFromJsonAsync<GameStatus>($"{configuration["GameServer"]}/status");
            MaxRow = Status.Board.Max(t => t.Location.Row);
            MaxCol = Status.Board.Max(t => t.Location.Column);

            if (Status.GameState == GameState.GameOver)
            {
                gameOverRequest = await httpClientFactory
               .CreateClient()
               .GetFromJsonAsync<GameOverRequest>($"{configuration["GameServer"]}/GameOverStats");
            }
        }


        public IActionResult OnPostStartGameAsync()
        {
            var client = httpClientFactory.CreateClient();
            Task.Run(()=>
                client.PostAsJsonAsync($"{configuration["GameServer"]}/startgame", new StartGameRequest { SecretCode = configuration["secretCode"] })
            );
            return new RedirectToPageResult("Index");
        }

        public IActionResult OnPostRestartGame()
        {
            var client = httpClientFactory.CreateClient();
            Task.Run(() =>
                client.PostAsJsonAsync($"{configuration["GameServer"]}/restartgame", new StartGameRequest { SecretCode = configuration["secretCode"] })
            );

            return new RedirectToPageResult("Index");
        }
    }
}

src/Visualizer/Pages/PlayByPlay.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Risk.Shared;

using Microsoft.Extensions.DependencyInjection;

namespace Visualizer.Pages
{
    public class PlayByPlayModeModel : PageModel
    {
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IConfiguration configuration;
        private readonly IMemoryCache memoryCache;

        public ColorGenerator ColorGenerator { get; }

        public PlayByPlayModeModel(IHttpClientFactory httpClientFactory, ColorGenerator colorGenerator, IConfiguration configuration, IMemoryCache memoryCache)
        {
            this.httpClientFactory = httpClientFactory;
            ColorGenerator = colorGenerator;
            this.configuration = configuration;
            this.memoryCache = memoryCache;
        }

        public GameStatus Status { get; set; }

        public GameStatus CurrentStatus { get; set; }


        public int MaxRow { get; private set; }
        public int MaxCol { get; private set; }

        public const string ListIndex = "Counter";

        public async Task OnGetAsync()
        {

            //Check if it exists in the cache
            List<GameStatus> GameStatusList;

            if (memoryCache.TryGetValue("Status", out GameStatusList))
            {
                CurrentStatus = GameStatusList[(int)HttpContext.Session.GetInt32(ListIndex)];
                MaxRow = CurrentStatus.Board.Max(t => t.Location.Row);
                MaxCol = CurrentStatus.Board.Max(t => t.Location.Column);
            }
            else
            {
                GameStatusList = await httpClientFactory
                .CreateClient()
                .GetFromJsonAsync<List<GameStatus>>($"{configuration["GameServer"]}/playByPlay");


                CurrentStatus = GameStatusList[0];

                MaxRow = CurrentStatus.Board.Max(t => t.Location.Row);
                MaxCol = CurrentStatus.Board.Max(t => t.Location.Column);


                MemoryCacheEntryOptions cacheEntryOptions = new MemoryCacheEntryOptions();
                cacheEntryOptions.AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(360);
                memoryCache.Set("Status", GameStatusList, cacheEntryOptions);
                HttpContext.Session.SetInt32(ListIndex, 0);
            }
        }


        public IActionResult OnPostPlayByPlayAsync(string action)
        {
            /*Implement  
             forwardOne,
             backwardOne,
             forwardEnd,
             backwardStart*/


            var GameStatusList = memoryCache.Get<List<GameStatus>>("Status");
            int CurrentIndex = (int)HttpContext.Session.GetInt32(ListIndex);

            if (action == "forwardOne")
            {
                CurrentIndex++;
                CurrentStatus = GameStatusList[CurrentIndex];
                HttpContext.Session.SetInt32(ListIndex, CurrentIndex);
            }
            else if (action == "forwardEnd")
            {
                CurrentIndex = GameStatusList.Count - 1;
                CurrentStatus = GameStatusList[CurrentIndex];

                HttpContext.Session.SetInt32(ListIndex, CurrentIndex);
            }
            else if (action == "backwardOne")
            {
                if (CurrentIndex != 0)
                {
                    CurrentIndex--;
                    CurrentStatus = GameStatusList[CurrentIndex];

                    HttpContext.Session.SetInt32(ListIndex, CurrentIndex);
                }
            }
            else if (action == "backwardStart")
            {
                CurrentIndex = 0;
                CurrentStatus = GameStatusList[CurrentIndex];
                HttpContext.Session.SetInt32(ListIndex, CurrentIndex);
            }

            return RedirectToPage();
        }

    }
}

src/Visualizer/Pages/Index.cshtml
@page
@using Risk.Shared
@model Visualizer.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Sample Client";
}
@if(Model.Status.GameState != GameState.GameOver)
{
    <meta http-equiv="refresh" content="1">
}
<style>
.location{
    font-size: 10pt;
    width: 48%;
    float: left;
}
.name {
    font-size: 14pt;
    color: blue
}
.armies {
    color: red;
    font-weight: bold;
    width: 48%;
    float: right;
    text-align: right;
}
.cell {
    min-width: 25px;
}
</style>

<h2>Game State: @Model.Status.GameState</h3>

@if(@Model.Status.GameState == Risk.Shared.GameState.Joining)
{
    <form method="post" asp-page-handler="StartGame">
        <button type="submit">Start Game</button>
    </form>
}

@if (@Model.Status.GameState == Risk.Shared.GameState.GameOver)
{
    <form method="get">
        <button type="submit" asp-page="./PlayByPlay">View Game Step By Step</button>
    </form>

    <form method="post" asp-page-handler="RestartGame">
        <button type="submit">Restart</button>
    </form>

    <p>@Model.gameOverRequest.WinnerName is Winner! </p>
    <p> Game took: @Model.gameOverRequest.GameDuration s </p>
}

<div class="playerStats">
    <table cellpadding="2px, 10px">
        <thead>
            <td>Player Name</td>
            <td>Territories</td>
            <td>Armies</td>
            <td>ContinentBonus</td>
            <td>FinalScore</td>
        </tr>
        @foreach (var p in Model.Status.PlayerStats.OrderByDescending(p=>p.Score))
        {
        <tr>
            <td>@p.Name</td>
            <td>@p.Territories</td>
            <td>@p.Armies</td>
            <td>@p.ContinentBonus</td>
            <td>@p.Score</td>
        </tr>
        }
    </table>
</div>

<div class="grid-container">
    <table border="1px" cellpadding="10px">
        @for (var row = 0; row <= Model.MaxRow; row++)
        {
        <tr>
            @for (var col = 0; col <= Model.MaxCol; col++)
            {
                var cell = Model.Status.Board.First(t => t.Location == new Location(row, col));
                var style =  string.IsNullOrEmpty(cell.OwnerName)
                    ? string.Empty
                    : $"style=background-color:{Html.Raw(Model.ColorGenerator.GetColor(cell.OwnerName))}";
                
                <td class="cell" @style>
                    <div class="location">@cell.Location</div>
                    <div class="armies">@cell.Armies</div>
                    <div class="name">@cell.OwnerName</div>
                </td>
            }
        </tr>
        }
    </table>
</div>

src/Visualizer/Pages/PlayByPlay.cshtml
@page "/PlayByPlay"
@using Risk.Shared
@model Visualizer.Pages.PlayByPlayModeModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "PlayByPlay";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    <title>
        PlayByPlay
    </title>
</head>
<body>



    <style>
        .location {
            font-size: 10pt;
            width: 48%;
            float: left;
        }

        .name {
            font-size: 14pt;
            color: blue
        }

        .armies {
            color: red;
            font-weight: bold;
            width: 48%;
            float: right;
            text-align: right;
        }

        .cell {
            min-width: 25px;
        }
    </style>

    <h2>Game State: @Model.CurrentStatus.GameState</h2>



    <form method="post" asp-page-handler="PlayByPlay">
        <button class="back-end" name="action" type="submit" value="backwardStart">Backward till start</button>
        <button class="back-one" name="action" type="submit" value="backwardOne">Backward 1 step</button>
        <button class="forw-one" name="action" type="submit" value="forwardOne">Forward 1</button>
        <button class="forw-end" name="action" type="submit" value="forwardEnd">Forward till end</button>

    </form>

    <br />
    <br />


    <form method="get">
        <button type="submit" asp-page="./Visualizer">Back to Visualizer</button>
    </form>


    <!--Player Stats-->

    <div class="playerStats">
        <table cellpadding="2px, 10px">
            <thead>
            <td>Player Name</td>
            <td>Territories</td>
            <td>Armies</td>
            <td>ContinentBonus</td>
            <td>FinalScore</td>
            </tr>
            @foreach (var p in Model.CurrentStatus.PlayerStats.OrderByDescending(p => p.Score))
            {
                <tr>
                    <td>@p.Name</td>
                    <td>@p.Territories</td>
                    <td>@p.Armies</td>
                    <td>@p.ContinentBonus</td>
                    <td>@p.Score</td>
                </tr>
            }
        </table>
    </div>

    <div>
        <h3>@Model.CurrentStatus.PlayerActionDescription</h3>
    </div>
    <!--Player Table Grid-->

<div class="grid-container">
    <table border="1px" cellpadding="10px">
        @for (var row = 0; row <= Model.MaxRow; row++)
        {
        <tr>
            @for (var col = 0; col <= Model.MaxCol; col++)
            {
                var cell = Model.CurrentStatus.Board.First(t => t.Location == new Location(row, col));
                var style =  string.IsNullOrEmpty(cell.OwnerName)
                    ? string.Empty
                    : $"style=background-color:{Html.Raw(Model.ColorGenerator.GetColor(cell.OwnerName))}";
                
                <td class="cell" @style>
                    <div class="location">@cell.Location</div>
                    <div class="armies">@cell.Armies</div>
                    <div class="name">@cell.OwnerName</div>
                </td>
            }
        </tr>
        }
    </table>
</div>


</body>
</html>

src/Visualizer/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
    <div style="margin-left: 20px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>